[package]
name = "vot-transport-queue"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
vot-transport-api = { path = "../vot-transport-api" }

[dev-dependencies]
vot-codec = { path = "../vot-codec" }
vot-transport-api = { path = "../vot-transport-api", features = ["test-util"] }

[lints]
workspace = true
