[package]
name = "vot-commit-object"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
s3-live = ["vot-object-store/s3-live"]

[dependencies]
vot-commit-model = { path = "../vot-commit-model" }
vot-journal = { path = "../vot-journal" }
vot-object-store = { path = "../vot-object-store" }

[lints]
workspace = true
