[package]
name = "vot-package"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
blake3 = { workspace = true, features = ["std"] }
vot-manifest = { path = "../vot-manifest" }
vot-verifier = { path = "../vot-verifier" }

[lints]
workspace = true
