[package]
name = "vot-platform-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Wdk_Storage_FileSystem", "Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Ioctl"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "=1.1.4", default-features = false, features = ["process", "std"] }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
undocumented_unsafe_blocks = "deny"
