[package]
name = "vot-commit-strict"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aligned-vec = "0.6.4"
blake3.workspace = true
rustix = { version = "1.1.4", features = ["fs"] }
sha2.workspace = true
vot-commit-model = { path = "../vot-commit-model" }

[lints]
workspace = true
