[package]
name = "vot-resume"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
blake3.workspace = true
fs4 = { version = "=1.1.0", default-features = false, features = ["sync"] }
vot-platform-fs = { path = "../vot-platform-fs" }
vot-resume-core = { path = "../vot-resume-core" }
vot-transport-api = { path = "../vot-transport-api" }
vot-transport-tcp = { path = "../vot-transport-tcp" }

[lints]
workspace = true
