[package]
name = "vot-codec"
version = "0.0.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
vot-fec = { path = "../vot-fec" }
vot-cbor = { path = "../vot-cbor" }
vot-manifest = { path = "../vot-manifest" }
vot-receipt = { path = "../vot-receipt", default-features = false }

[lints]
workspace = true
