gitignore = true
minimum_test_timeout = 20.0
timeout_multiplier = 4.0
exclude_re = ["live::registration", "live::send_owned", "(windows|unsupported)_rename_noreplace", "NativeOperations.*sync_(file|parent)"]
exclude_globs = ["crates/vot-cli/src/main.rs"]
