[package]
name = "vot-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
vot-manifest = { path = "../vot-manifest" }
vot-pack = { path = "../vot-pack" }
vot-receipt = { path = "../vot-receipt" }
vot-scheduler = { path = "../vot-scheduler" }
vot-transport-api = { path = "../vot-transport-api" }
vot-verifier = { path = "../vot-verifier" }

[lints]
workspace = true
