[package]
name = "vot-manifest"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
vot-cbor = { path = "../vot-cbor" }
blake3.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
cap = "=0.1.2"

[lints]
workspace = true
