[package]
name = "vot-object-store"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[features]
s3-live = ["dep:aws-sdk-s3", "dep:base64", "dep:tokio"]

[dependencies]
aws-sdk-s3 = { version = "=1.120.0", default-features = false, features = ["default-https-client", "rt-tokio"], optional = true }
base64 = { version = "0.23.0", optional = true }
tokio = { version = "1.45.1", features = ["rt-multi-thread"], optional = true }
vot-journal = { path = "../vot-journal" }

[lints]
workspace = true
